version: '3'

services:
  pokedexapp:
    container_name: pokedexapp
    build: 
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    depends_on:
      - db
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}

  db:
    image: mongo:5
    container_name: mongo-poke
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - poke-vol:/data/db

volumes:
  poke-vol:
    external: false
